version: 0.2

phases:
  install:
    runtime-version:
      python: 3.12
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt -t package/
  build:
    commands:
      - echo "Building Lambda package"
      - cp handler.py package/
      - cd package && zip -r ../function.zip . && cd ..
artifacts:
  files:
    - function.zip
